### ISSUE TITLE
[TODO] Main features for 1.0.0 release

### ISSUE THREAD

**Issue by alfonmga** [AMGAVentures/saas-boilerplate#303]
- [x] Login
- [x] Signup
- [x] Signup email verification
- [x] Forgot password
- [x] Change account password
- [x] Set account nickname 
- [x] Update account personal details
- [x] Update account preferences
- [x] Set allowed account notifications
- [x] Trial period
- [x] Show trial expiring warning in UI
- [x] Handle trial period lifecycle 
- [x] Plans list
- [x] Subscribe to plan [Paddle.com]
- [x] Upgrade and downgrade plan [Paddle.com]
- [x] Cancel subscription renewal [Paddle.com]
- [x] Pay plan with cryptocurrency
- [x] Handle subscription lifecycle
- [x] Limit access to product features based on user subscription plan type
- [X] User timezones
- [x] 2FA
- [x] Contact support
- [x] API secret key (view and regenerate)
- [x] Pricing page
- [x] Product changelog [headwayapp.co]
- [x] Product status page [uptimerobot.com]
- [x] Homepage
- [x] Blog
- [x] FAQ
- [x] About us
- [x] Legal terms (Privacy Policy and Terms of Service)

**Comment by alfonmga** [comment]
Everything is ready 🎉
**1.0.0** could be launched today or so, before I do the final review.

**Comment by alfonmga** [comment]
Merged at #330 PR
